name: Publish Docker Image on PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - develop

jobs:
  build-and-push:
    # Hanya berjalan jika PR ditutup karena di-merge
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/publish-core.yml
    with:
      target_branch: ${{ github.event.pull_request.base.ref }}
      deploy_reason: ${{ github.event.pull_request.title }}
      deploy_url: ${{ github.event.pull_request.html_url }}
    secrets: inherit
